node {
  def mvnHome
  
  stage('Preparation') { // for display purposes
     // Get some code from a GitHub repository
     nexus 'https://localhost:8081/repository/repodatapower/'
  }
  
  stage('Importar') {
 //COMANDO PARA SUBIR ARCHIVO A DATAPOWER
        sh 'curl –H "Content-Type: text/xml" --data-binary @importardatapower.xml https://192.168.1.22:5550/service/mgmt/current -u admin:admin123 -k'
	sh mvn release:clean
       sh mvn release:prepare
        sh mvn deploy

mvn 
  }
  

}
